# Generated by Django 6.0.7 on 2026-07-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('giftcard', 'Giftcard'), ('subscription', 'Subscription'), ('topup', 'TopUp')], default='giftcard', max_length=20),
        ),
    ]
