# Generated by Django 6.0.7 on 2026-07-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_slug_alter_product_slug'),
        ('products', '0002_alter_product_product_type'),
    ]

    operations = [
    ]
