# Generated by Django 6.0.7 on 2026-07-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_created_at_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_games',
            field=models.TextField(blank=True),
        ),
    ]
