# Generated by Django 6.0.7 on 2026-07-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number'),
        ('accounts', '0006_alter_user_phone_number'),
    ]

    operations = [
    ]
